[package]
name = "iot-packet-verifier"
version = "0.1.0"
edition = "2021"
description = "Validate LoRaWAN traffic for Helium Packet-Router (HPR) business ops"
authors = ["Helium <info@helium.com>"]
license = "Apache-2.0"

[[bin]]
name = "iot_packet_verifier"
path = "src/main.rs"
doc = false

[features]
# Generate protobuf files via: cargo test --feature=sample-data
sample-data = []

[dependencies]
#aws-config = "0"
#aws-sdk-s3 = "0"
#clap = {version = "3", features = ["derive"]}
#dotenv = "0"
futures = "*"
futures-core = "*"
futures-util = "*"

# FIXME
# helium-proto = {git="https://github.com/helium/proto", branch="master", features=["services"]}
# helium-proto = {git="https://github.com/helium/proto", branch="macpie/packet_router", features=["services"]}
helium-proto = {git="https://github.com/helium/proto", branch="dpezely/packet-verifier", features=["services"]}
#helium-proto = {path="../../../helium/proto", features=["services"]}

# lazy_static = "1"

poc-store = {path = "../store"}
#poc-metrics = {path = "../metrics"}

prost = "0"
bytes = "*"

serde =  {version = "1", features=["derive"]}
serde_json = "1"

slog = "2"
slog-async = "2"
slog-term = "2"
slog-syslog = "0"
slog-scope = "4"
slog-stdlog = "4"

#thiserror = "1"

tokio = { version = "1", default-features=false, features=["fs", "macros", "signal", "rt", "process", "time"] }
tokio-stream = {version = "0", features = ["fs"] }
tokio-util = "0"
