[package]
name = "iot-packet-verifier"
version = "0.1.0"
description = "Verify LoRaWAN traffic for Helium Packet-Router (HPR) operations"
edition.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "iot_packet_verifier"
path = "src/main.rs"
doc = false

[dependencies]
async-compression = {version="*", optional=true}
chrono = {workspace=true}
clap = {workspace=true}
config = {workspace=true}
file-store = {path="../file_store"}
futures = {workspace=true}
helium-crypto = {workspace=true}
helium-proto = {workspace=true}
poc-metrics = {path="../metrics"}
prost = {workspace=true}
serde = {workspace=true}
thiserror = {workspace=true}
tokio = {workspace=true}
tonic = {workspace=true}
tracing = {workspace=true}
tracing-subscriber = {workspace=true}
triggered = {workspace=true}
